AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sistema de Microserviços com Funções Lambda

# Parâmetros globais
Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
  RoleArn:
    Type: String
    Default: arn:aws:iam::058264100464:role/LabRole
  QueueName:
    Type: String
    Default: register-queue
  

# Recursos principais
Resources:
  # Importar template de funções Lambda
  LambdaFunctions:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/functions.yaml
      Parameters:
        Env: !Ref Env
        RoleArn: !Ref RoleArn
        QueueUrl: !Ref QueueUrl # Passa a URL da fila SQS como parâmetro para as funções Lambda
        QueueARN: !Ref SQSQueueARN

    SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName # Nome da fila SQS
      ReceiveMessageWaitTimeSeconds: 20 # Tempo de espera para verificar novas mensagens na fila
      VisibilityTimeout: 60 # Tempo de visibilidade da mensagem na fila
      MessageRetentionPeriod: 86400 # Tempo de retenção da mensagem na fila (1 dia)

Outputs:
  QueueUrl:
    Value: !Ref SqsQueue # URL da fila SQS
  SQSQueueARN:
    Description: "ARN da fila SQS"
    Value: !GetAtt SqsQueue.Arn